name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
      ref: feature/DSI-3601-ArmTemplateOverride
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config
      ref: master

trigger:
  branches:
    include:
    - develop
    - master
    
pr:
  branches:
    exclude:
    - develop

variables:
- group: platform-global

stages:
- template: /Application/node/stages/signin-master-gateway-stage.yml@devopsTemplates
  parameters:
    applicationName: interactions
    resourceGroupSuffix: int-failover
    armTemplateName: template-failover.json
    hostNameComponent: int
    customTemplateBaseUri:
      - dev
    enableVirtualNetworkIntegration:
      - dev
    enablePrivateEndpoint:
      - dev